version: "3"
services:
    web:
        build: .
        volumes:
            - ./app:/var/www/app
        ports:
            - "81:80"
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: "root"
        volumes:
            - ./app/scripts:/scripts
