version: "3"
services:
    web:
        depends_on:
            - mysql
        build: .
        volumes:
            - ./app/public:/var/www/html
            - ./app/private:/var/www/cbcn-private
            - ./app/core:/var/www/cbcn-core
            - ./app/lib:/var/www/cbcn-lib
            - ./app/scripts:/etc/cbcn/scripts
            - web_static:/var/www/html/static
        ports:
            - "81:80"
            - "444:443"
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: "root"
        volumes:
            - ./app/scripts:/scripts
            - ./data/mysql:/var/lib/mysql
volumes:
    web_static:
