version: "3"
services:
    web:
        build: .
        volumes:
            - ./app/public:/var/www/html
            - ./app/private:/var/www/cbcn-private
            - ./app/core:/var/www/cbcn-core
            - ./app/lib:/var/www/cbcn-lib
            - ./app/scripts:/etc/cbcn/scripts
        ports:
            - "81:80"
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: "root"
        volumes:
            - ./app/scripts:/scripts
